### ISSUE TITLE
Maven test failures for fresh builds

### ISSUE THREAD

**Issue by aknz** [CSCfi/shibboleth-idp-oidc-extension#26] opened 2019-08-06 11:21 UTC
Using Maven 3.5.4 with OpenJDK 11.0.4 after a successful git clone running `mvn package` which will execute for a good while without error until eventually at "idp-oidc-extension-api":

```
[INFO] Running TestSuite
[ERROR] Tests run: 141, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 36.141 s <<< FAILURE! - in TestSuite
[ERROR] testSuccessNoSecurity(org.geant.idpextension.oidc.metadata.resolver.RemoteJwkSetCacheTest)  Time elapsed: 0.309 s  <<< FAILURE!
java.lang.AssertionError: expected object to not be null
	at org.geant.idpextension.oidc.metadata.resolver.RemoteJwkSetCacheTest.testSuccessNoSecurity(RemoteJwkSetCacheTest.java:100)
```

Regardless how often the package is being built, at the following step it always identifies changes:
```
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ idp-oidc-extension-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 117 source files to /home/xxx/shibboleth-idp-oidc-extension/idp-oidc-extension-api/target/classes
[INFO] /home/xxx/shibboleth-idp-oidc-extension/idp-oidc-extension-api/src/main/java/org/geant/idpextension/oidc/profile/context/navigate/DefaultRequestMaxAgeLookupFunction.java: Some input files use or override a deprecated API.
[INFO] /home/xxx/shibboleth-idp-oidc-extension/idp-oidc-extension-api/src/main/java/org/geant/idpextension/oidc/profile/context/navigate/DefaultRequestMaxAgeLookupFunction.java: Recompile with -Xlint:deprecation for details.
```

Calling `mvn package` often enough (maybe 5-6 times), it may also go past the above error but fails nevertheless at "idp-oidc-extension-impl":
```
[INFO] Running TestSuite
[ERROR] Tests run: 532, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 266.45 s <<< FAILURE! - in TestSuite
[ERROR] testWithAuthorizationCodeFlow(org.geant.idpextension.oidc.profile.flow.AuthorizeFlowTest)  Time elapsed: 1.774 s  <<< FAILURE!
java.lang.AssertionError: expected [CommitResponse] but found [ErrorView]
	at org.geant.idpextension.oidc.profile.flow.AuthorizeFlowTest.testWithAuthorizationCodeFlow(AuthorizeFlowTest.java:81)

[ERROR] testRevokeAccessToken(org.geant.idpextension.oauth2.profile.impl.RevokeTokenTest)  Time elapsed: 0.024 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.geant.idpextension.oauth2.profile.impl.RevokeTokenTest.testRevokeAccessToken(RevokeTokenTest.java:132)

[ERROR] testRevokeRefreshToken(org.geant.idpextension.oauth2.profile.impl.RevokeTokenTest)  Time elapsed: 0.027 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.geant.idpextension.oauth2.profile.impl.RevokeTokenTest.testRevokeRefreshToken(RevokeTokenTest.java:143)
```

Currently running this on SuSE's Tumbleweed, but had the same happen under CentOS 7 and also Fedora 30, so I can likely rule out some strange distro behavior or strange customization issues within an older system installation.

Expected behavior for me would be, of course, that it builds without error on a fresh default install or a hint if more configuration or setup is needed before it can be built.

**Comment by hjmikkon** [comment] 2019-08-09 10:48
I managed to reproduce this issue: it seemed to be caused by the fact that some tests were running so slowly that the internal data expired during the tests. The main cause for the slowness at least in my case was the slow random generator, and I could fix it by editing the java.security configuration and changing the value of *securerandom.source* to:

securerandom.source=file:/dev/urandom

(By default it was /dev/random). Can you try the same in your environment? In CentOS7 with OpenJDK11 installed from the repository, the file was located at: /usr/lib/jvm/java-11/conf/security/java.security

**Comment by aknz** [comment] 2019-08-09 11:32
In SuSE Tumbleweed I've found the configuration file at /usr/lib64/jvm/java-11-openjdk-11/conf/security/java.security but after changing the randomness source to /dev/urandom the build still fails with the same error. 

But good point about the performance: Due to your comment I think it makes sense to blame the machine I am running this on (an older dual-core ThinkPad) as the possible cause of those errors since the execution time of the tests is still the same as before (37s for idp-oidc-extension-api's TestSuite), even with /dev/urandom. 

What would be the target time be (roughly) for running this TestSuite?

Or is there another way to make the tests run sucessfully, regardless of the performance of the machine they are executed on?

I'll also try to find another system to run this on in the meantime. In addition to the OSes I had listed above I had tried it on a Chromebook running Linux, but it makes sense that it fails there as well due to its even lower performance.

**Comment by hjmikkon** [comment] 2019-08-09 12:39
You can see the build logs of the Travis-builds here:

https://travis-ci.org/CSCfi/shibboleth-idp-oidc-extension

So, for the api-module the tests took 4.252s and for 49.656s for the impl-module. With an Openstack VM having 2 VCPUs and 2 gigs of RAM, I already get a bit faster times.

**Comment by hjmikkon** [comment] 2020-02-07 13:06
Closing this issue: The code is currently built in the Shibboleth project's CI system with multiple platform + Java combinations, and any issues arising from there will be fixed.

**Closed as completed by hjmikkon** 2020-02-07 13:06 UTC
